# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [Scoobydowsky]

# Optional: add other platforms (one entry each)
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
# custom: ["https://your-link.com"]
